name: Restore

on:
  workflow_dispatch:

jobs:
  restore-workflows:
    runs-on: ubuntu-24.04
    name: Restore Workflows from Github to n8n
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 'lts/*'

      - name: Install n8n CLI
        run: |
          curl -sSLf https://raw.github.com/edenreich/n8n-cli/main/install.sh | sh

      - name: List available workflows
        run: |
          echo "Available workflows in repository:"
          ls -la workflows/

      - name: Restore all workflows to n8n instance
        env:
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
          N8N_INSTANCE_URL: ${{ secrets.N8N_INSTANCE_URL }}
        run: |
          echo "Restoring all workflows to n8n instance..."
          n8n workflows sync --directory workflows/ --refresh=false
          echo "All workflows restored successfully!"
