// Code generated by counterfeiter. DO NOT EDIT.
package clientfakes

import (
	"sync"

	"github.com/edenreich/n8n-cli/n8n"
)

type FakeClientInterface struct {
	ActivateWorkflowStub        func(string) (*n8n.Workflow, error)
	activateWorkflowMutex       sync.RWMutex
	activateWorkflowArgsForCall []struct {
		arg1 string
	}
	activateWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	activateWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	CreateWorkflowStub        func(*n8n.Workflow) (*n8n.Workflow, error)
	createWorkflowMutex       sync.RWMutex
	createWorkflowArgsForCall []struct {
		arg1 *n8n.Workflow
	}
	createWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	createWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	DeactivateWorkflowStub        func(string) (*n8n.Workflow, error)
	deactivateWorkflowMutex       sync.RWMutex
	deactivateWorkflowArgsForCall []struct {
		arg1 string
	}
	deactivateWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	deactivateWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	DeleteWorkflowStub        func(string) error
	deleteWorkflowMutex       sync.RWMutex
	deleteWorkflowArgsForCall []struct {
		arg1 string
	}
	deleteWorkflowReturns struct {
		result1 error
	}
	deleteWorkflowReturnsOnCall map[int]struct {
		result1 error
	}
	GetWorkflowsStub        func() (*n8n.WorkflowList, error)
	getWorkflowsMutex       sync.RWMutex
	getWorkflowsArgsForCall []struct {
	}
	getWorkflowsReturns struct {
		result1 *n8n.WorkflowList
		result2 error
	}
	getWorkflowsReturnsOnCall map[int]struct {
		result1 *n8n.WorkflowList
		result2 error
	}
	UpdateWorkflowStub        func(string, *n8n.Workflow) (*n8n.Workflow, error)
	updateWorkflowMutex       sync.RWMutex
	updateWorkflowArgsForCall []struct {
		arg1 string
		arg2 *n8n.Workflow
	}
	updateWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	updateWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClientInterface) ActivateWorkflow(arg1 string) (*n8n.Workflow, error) {
	fake.activateWorkflowMutex.Lock()
	ret, specificReturn := fake.activateWorkflowReturnsOnCall[len(fake.activateWorkflowArgsForCall)]
	fake.activateWorkflowArgsForCall = append(fake.activateWorkflowArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ActivateWorkflowStub
	fakeReturns := fake.activateWorkflowReturns
	fake.recordInvocation("ActivateWorkflow", []interface{}{arg1})
	fake.activateWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) ActivateWorkflowCallCount() int {
	fake.activateWorkflowMutex.RLock()
	defer fake.activateWorkflowMutex.RUnlock()
	return len(fake.activateWorkflowArgsForCall)
}

func (fake *FakeClientInterface) ActivateWorkflowCalls(stub func(string) (*n8n.Workflow, error)) {
	fake.activateWorkflowMutex.Lock()
	defer fake.activateWorkflowMutex.Unlock()
	fake.ActivateWorkflowStub = stub
}

func (fake *FakeClientInterface) ActivateWorkflowArgsForCall(i int) string {
	fake.activateWorkflowMutex.RLock()
	defer fake.activateWorkflowMutex.RUnlock()
	argsForCall := fake.activateWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) ActivateWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.activateWorkflowMutex.Lock()
	defer fake.activateWorkflowMutex.Unlock()
	fake.ActivateWorkflowStub = nil
	fake.activateWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) ActivateWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.activateWorkflowMutex.Lock()
	defer fake.activateWorkflowMutex.Unlock()
	fake.ActivateWorkflowStub = nil
	if fake.activateWorkflowReturnsOnCall == nil {
		fake.activateWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.activateWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateWorkflow(arg1 *n8n.Workflow) (*n8n.Workflow, error) {
	fake.createWorkflowMutex.Lock()
	ret, specificReturn := fake.createWorkflowReturnsOnCall[len(fake.createWorkflowArgsForCall)]
	fake.createWorkflowArgsForCall = append(fake.createWorkflowArgsForCall, struct {
		arg1 *n8n.Workflow
	}{arg1})
	stub := fake.CreateWorkflowStub
	fakeReturns := fake.createWorkflowReturns
	fake.recordInvocation("CreateWorkflow", []interface{}{arg1})
	fake.createWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) CreateWorkflowCallCount() int {
	fake.createWorkflowMutex.RLock()
	defer fake.createWorkflowMutex.RUnlock()
	return len(fake.createWorkflowArgsForCall)
}

func (fake *FakeClientInterface) CreateWorkflowCalls(stub func(*n8n.Workflow) (*n8n.Workflow, error)) {
	fake.createWorkflowMutex.Lock()
	defer fake.createWorkflowMutex.Unlock()
	fake.CreateWorkflowStub = stub
}

func (fake *FakeClientInterface) CreateWorkflowArgsForCall(i int) *n8n.Workflow {
	fake.createWorkflowMutex.RLock()
	defer fake.createWorkflowMutex.RUnlock()
	argsForCall := fake.createWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) CreateWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.createWorkflowMutex.Lock()
	defer fake.createWorkflowMutex.Unlock()
	fake.CreateWorkflowStub = nil
	fake.createWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.createWorkflowMutex.Lock()
	defer fake.createWorkflowMutex.Unlock()
	fake.CreateWorkflowStub = nil
	if fake.createWorkflowReturnsOnCall == nil {
		fake.createWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.createWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) DeactivateWorkflow(arg1 string) (*n8n.Workflow, error) {
	fake.deactivateWorkflowMutex.Lock()
	ret, specificReturn := fake.deactivateWorkflowReturnsOnCall[len(fake.deactivateWorkflowArgsForCall)]
	fake.deactivateWorkflowArgsForCall = append(fake.deactivateWorkflowArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeactivateWorkflowStub
	fakeReturns := fake.deactivateWorkflowReturns
	fake.recordInvocation("DeactivateWorkflow", []interface{}{arg1})
	fake.deactivateWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) DeactivateWorkflowCallCount() int {
	fake.deactivateWorkflowMutex.RLock()
	defer fake.deactivateWorkflowMutex.RUnlock()
	return len(fake.deactivateWorkflowArgsForCall)
}

func (fake *FakeClientInterface) DeactivateWorkflowCalls(stub func(string) (*n8n.Workflow, error)) {
	fake.deactivateWorkflowMutex.Lock()
	defer fake.deactivateWorkflowMutex.Unlock()
	fake.DeactivateWorkflowStub = stub
}

func (fake *FakeClientInterface) DeactivateWorkflowArgsForCall(i int) string {
	fake.deactivateWorkflowMutex.RLock()
	defer fake.deactivateWorkflowMutex.RUnlock()
	argsForCall := fake.deactivateWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) DeactivateWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.deactivateWorkflowMutex.Lock()
	defer fake.deactivateWorkflowMutex.Unlock()
	fake.DeactivateWorkflowStub = nil
	fake.deactivateWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) DeactivateWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.deactivateWorkflowMutex.Lock()
	defer fake.deactivateWorkflowMutex.Unlock()
	fake.DeactivateWorkflowStub = nil
	if fake.deactivateWorkflowReturnsOnCall == nil {
		fake.deactivateWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.deactivateWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) DeleteWorkflow(arg1 string) error {
	fake.deleteWorkflowMutex.Lock()
	ret, specificReturn := fake.deleteWorkflowReturnsOnCall[len(fake.deleteWorkflowArgsForCall)]
	fake.deleteWorkflowArgsForCall = append(fake.deleteWorkflowArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteWorkflowStub
	fakeReturns := fake.deleteWorkflowReturns
	fake.recordInvocation("DeleteWorkflow", []interface{}{arg1})
	fake.deleteWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientInterface) DeleteWorkflowCallCount() int {
	fake.deleteWorkflowMutex.RLock()
	defer fake.deleteWorkflowMutex.RUnlock()
	return len(fake.deleteWorkflowArgsForCall)
}

func (fake *FakeClientInterface) DeleteWorkflowCalls(stub func(string) error) {
	fake.deleteWorkflowMutex.Lock()
	defer fake.deleteWorkflowMutex.Unlock()
	fake.DeleteWorkflowStub = stub
}

func (fake *FakeClientInterface) DeleteWorkflowArgsForCall(i int) string {
	fake.deleteWorkflowMutex.RLock()
	defer fake.deleteWorkflowMutex.RUnlock()
	argsForCall := fake.deleteWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) DeleteWorkflowReturns(result1 error) {
	fake.deleteWorkflowMutex.Lock()
	defer fake.deleteWorkflowMutex.Unlock()
	fake.DeleteWorkflowStub = nil
	fake.deleteWorkflowReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) DeleteWorkflowReturnsOnCall(i int, result1 error) {
	fake.deleteWorkflowMutex.Lock()
	defer fake.deleteWorkflowMutex.Unlock()
	fake.DeleteWorkflowStub = nil
	if fake.deleteWorkflowReturnsOnCall == nil {
		fake.deleteWorkflowReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteWorkflowReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) GetWorkflows() (*n8n.WorkflowList, error) {
	fake.getWorkflowsMutex.Lock()
	ret, specificReturn := fake.getWorkflowsReturnsOnCall[len(fake.getWorkflowsArgsForCall)]
	fake.getWorkflowsArgsForCall = append(fake.getWorkflowsArgsForCall, struct {
	}{})
	stub := fake.GetWorkflowsStub
	fakeReturns := fake.getWorkflowsReturns
	fake.recordInvocation("GetWorkflows", []interface{}{})
	fake.getWorkflowsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetWorkflowsCallCount() int {
	fake.getWorkflowsMutex.RLock()
	defer fake.getWorkflowsMutex.RUnlock()
	return len(fake.getWorkflowsArgsForCall)
}

func (fake *FakeClientInterface) GetWorkflowsCalls(stub func() (*n8n.WorkflowList, error)) {
	fake.getWorkflowsMutex.Lock()
	defer fake.getWorkflowsMutex.Unlock()
	fake.GetWorkflowsStub = stub
}

func (fake *FakeClientInterface) GetWorkflowsReturns(result1 *n8n.WorkflowList, result2 error) {
	fake.getWorkflowsMutex.Lock()
	defer fake.getWorkflowsMutex.Unlock()
	fake.GetWorkflowsStub = nil
	fake.getWorkflowsReturns = struct {
		result1 *n8n.WorkflowList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetWorkflowsReturnsOnCall(i int, result1 *n8n.WorkflowList, result2 error) {
	fake.getWorkflowsMutex.Lock()
	defer fake.getWorkflowsMutex.Unlock()
	fake.GetWorkflowsStub = nil
	if fake.getWorkflowsReturnsOnCall == nil {
		fake.getWorkflowsReturnsOnCall = make(map[int]struct {
			result1 *n8n.WorkflowList
			result2 error
		})
	}
	fake.getWorkflowsReturnsOnCall[i] = struct {
		result1 *n8n.WorkflowList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) UpdateWorkflow(arg1 string, arg2 *n8n.Workflow) (*n8n.Workflow, error) {
	fake.updateWorkflowMutex.Lock()
	ret, specificReturn := fake.updateWorkflowReturnsOnCall[len(fake.updateWorkflowArgsForCall)]
	fake.updateWorkflowArgsForCall = append(fake.updateWorkflowArgsForCall, struct {
		arg1 string
		arg2 *n8n.Workflow
	}{arg1, arg2})
	stub := fake.UpdateWorkflowStub
	fakeReturns := fake.updateWorkflowReturns
	fake.recordInvocation("UpdateWorkflow", []interface{}{arg1, arg2})
	fake.updateWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) UpdateWorkflowCallCount() int {
	fake.updateWorkflowMutex.RLock()
	defer fake.updateWorkflowMutex.RUnlock()
	return len(fake.updateWorkflowArgsForCall)
}

func (fake *FakeClientInterface) UpdateWorkflowCalls(stub func(string, *n8n.Workflow) (*n8n.Workflow, error)) {
	fake.updateWorkflowMutex.Lock()
	defer fake.updateWorkflowMutex.Unlock()
	fake.UpdateWorkflowStub = stub
}

func (fake *FakeClientInterface) UpdateWorkflowArgsForCall(i int) (string, *n8n.Workflow) {
	fake.updateWorkflowMutex.RLock()
	defer fake.updateWorkflowMutex.RUnlock()
	argsForCall := fake.updateWorkflowArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) UpdateWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.updateWorkflowMutex.Lock()
	defer fake.updateWorkflowMutex.Unlock()
	fake.UpdateWorkflowStub = nil
	fake.updateWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) UpdateWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.updateWorkflowMutex.Lock()
	defer fake.updateWorkflowMutex.Unlock()
	fake.UpdateWorkflowStub = nil
	if fake.updateWorkflowReturnsOnCall == nil {
		fake.updateWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.updateWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.activateWorkflowMutex.RLock()
	defer fake.activateWorkflowMutex.RUnlock()
	fake.createWorkflowMutex.RLock()
	defer fake.createWorkflowMutex.RUnlock()
	fake.deactivateWorkflowMutex.RLock()
	defer fake.deactivateWorkflowMutex.RUnlock()
	fake.deleteWorkflowMutex.RLock()
	defer fake.deleteWorkflowMutex.RUnlock()
	fake.getWorkflowsMutex.RLock()
	defer fake.getWorkflowsMutex.RUnlock()
	fake.updateWorkflowMutex.RLock()
	defer fake.updateWorkflowMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClientInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ n8n.ClientInterface = new(FakeClientInterface)
