version = 1

[install]
go.pkg-path = "go"
go.version = "^1.25.0"

golangci-lint.pkg-path = "golangci-lint"
golangci-lint.version = "^2.5.0"

claude-code.pkg-path = "claude-code"
claude-code.version = "^2.0.8"

act.pkg-path = "act"
act.version = "^0.2.82"
