version: '3'

dotenv:
  - .env

vars:
  WORKFLOW_DIR: workflows

tasks:
  sync:
    desc: Sync workflows to n8n instance
    cmds:
      - echo "Syncing workflows to n8n instance..."
      - n8n workflows sync --directory {{.WORKFLOW_DIR}}/

  sync-dry-run:
    desc: Preview sync without making changes
    cmds:
      - echo "Previewing sync (dry run)..."
      - n8n workflows sync --directory {{.WORKFLOW_DIR}}/ --dry-run

  refresh:
    desc: Refresh local workflows from n8n instance
    cmds:
      - echo "Refreshing workflows from n8n instance..."
      - n8n workflows refresh --directory {{.WORKFLOW_DIR}}/ --output yaml

  refresh-all:
    desc: Refresh all workflows from n8n instance (including new ones)
    cmds:
      - echo "Refreshing all workflows from n8n instance..."
      - n8n workflows refresh --directory {{.WORKFLOW_DIR}}/ --output yaml --all

  list:
    desc: List workflows from n8n instance
    cmds:
      - echo "Listing workflows from n8n instance..."
      - n8n workflows list

  executions:
    desc: View workflow execution history
    cmds:
      - echo "Fetching workflow execution history..."
      - n8n workflows executions

  preview:
    desc: Start a local web server to preview the HTML form
    cmds:
      - echo "Starting web server on http://localhost:8000..."
      - python3 -m http.server 8000 || python -m SimpleHTTPServer 8000

  setup-env:
    desc: Create a template .env file (won't overwrite existing)
    cmds:
      - |
        if [ ! -f .env ]; then
          echo "Creating template .env file..."
          echo "N8N_API_KEY=your_api_key_here" > .env
          echo "N8N_INSTANCE_URL=https://your-instance.n8n.cloud" >> .env
          echo "Created .env file. Please update with your actual credentials."
        else
          echo ".env file already exists. Not overwriting."
        fi

  up:
    desc: Start n8n and mailhog with docker-compose
    cmds:
      - echo "Starting n8n and mailhog..."
      - docker-compose up -d
      - echo "n8n is available at http://localhost:5678"
      - echo "Mailhog is available at http://localhost:8025"

  down:
    desc: Stop n8n and mailhog containers
    cmds:
      - echo "Stopping containers..."
      - docker-compose down

  logs:
    desc: Show logs from n8n container
    cmds:
      - docker-compose logs -f n8n

  logs-mail:
    desc: Show logs from mailhog container
    cmds:
      - docker-compose logs -f mailhog

  restart:
    desc: Restart n8n and mailhog containers
    cmds:
      - task: down
      - task: up

  clean:
    desc: Remove containers and volumes
    cmds:
      - echo "Removing containers and volumes..."
      - docker-compose down -v

  help:
    desc: Display available tasks
    silent: true
    cmds:
      - task --list
