---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.24"

      - name: Install GolangCI Lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.5

      - name: Lint
        run: golangci-lint run

      - name: Build
        run: go build -v ./...
